# Generated by Django 4.2.10 on 2025-05-06 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latefee',
            name='borrow_id',
        ),
        migrations.RemoveField(
            model_name='latefee',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='latefee',
            name='waived_by',
        ),
        migrations.RenameField(
            model_name='bookauthor',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='bookauthor',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookgenre',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookgenre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='borrowing',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='bookauthor',
            unique_together={('book', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='bookgenre',
            unique_together={('book', 'genre')},
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(through='LibraryManagement.BookAuthor', to='LibraryManagement.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(through='LibraryManagement.BookGenre', to='LibraryManagement.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryManagement.publisher'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryManagement.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ONLINE', 'Online')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BORROW', 'Borrow'), ('RETURN', 'Return'), ('FEE', 'Fee')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('USER', 'Regular User'), ('AUTHOR', 'Author'), ('ADMIN', 'Administrator')], default='USER', max_length=10),
        ),
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
        migrations.DeleteModel(
            name='LateFee',
        ),
    ]
